### ISSUE TITLE
dead link: http://developer.tidepool.io/tidepool-components/StartingUpServices.html

### ISSUE THREAD

**Issue by yeagerm** [tidepool-org/hub#115]
on:
http://developer.tidepool.io/tidepool-components/

should link to:
http://developer.tidepool.io/starting-up-services/

**Comment by kentquirk** [comment]
Thanks. It's been fixed.

On Thu, Jan 29, 2015 at 1:38 PM, yeagerm <notifications@github.com> wrote:

> on:
> http://developer.tidepool.io/tidepool-components/
>
> should link to:
> http://developer.tidepool.io/starting-up-services/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tidepool-org/hub/issues/115>.
>



-- 
Kent Quirk
VP of Engineering, Tidepool

Tidepool is an open source, not-for-profit effort to build an open data
platform and better applications to reduce the burden of Type 1 Diabetes.
