### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by fgentzel** [tidepool-org/hub#116]
Apologies, am new to all this and trying to install on Mac 10.10.2 (14C109) according to the instructions but "update_current_tidepool_repos.sh" fails on jellyfish and I have been unable to figure out why. Here is the relevant part of the log:

5687 error Darwin 14.1.0
5688 error argv "node" "/Users/fredrikgentzel/.node/bin/npm" "install"
5689 error node v0.12.0
5690 error npm  v2.6.1
5691 error code ELIFECYCLE
5692 error node-expat@2.0.0 install: `node-gyp rebuild`
5692 error Exit status 1
5693 error Failed at the node-expat@2.0.0 install script 'node-gyp rebuild'.
5693 error This is most likely a problem with the node-expat package,
5693 error not with npm itself.
5693 error Tell the author that this fails on your system:
5693 error     node-gyp rebuild
5693 error You can get their info via:
5693 error     npm owner ls node-expat
5693 error There is likely additional logging output above.

Any ideas on how to fix?

**Comment by jh-bate** [comment]
Hi,

One thing to note is that we are in the process of updating dependancies
and are still targeting node v0.10 at the moment. It looks like your
running with v0.12.0??

Maybe try running against an older version of node and see if that works
for you. If that is a red herring let me know and I will take a closer look
tomorrow.

Thanks
Jamie

**Comment by fgentzel** [comment]
Perfect - node v0.10 works....thanks a million!

**Comment by jh-bate** [comment]
awesome - glad to hear. We better get busy and finish updating the
dependancies :)
