### ISSUE TITLE
Which version of node.js is required for latest builds?

### ISSUE THREAD

**Issue by darinkrauss** [tidepool-org/hub#118]
I recently updated to version 12.0 of node.js (yep, probably a rash mistake) and am getting a variety of errors when trying to build. What is the greatest version of node.js that will actually build the various Tidepool projects?

**Comment by jh-bate** [comment]
Hi, 

we are in the process of updating all repos to use v 12.0 (and are very close) but at the moment its running on v 10.0

**Comment by jh-bate** [comment]
and for better context here is the card we are working through at the moment which lists all the repos and where they are at with regards to the upgrade https://trello.com/c/dbPZldZh

**Comment by darinkrauss** [comment]
Cool, got it working.  Downgraded to v10.0 and got it to work.  Thanks!

**Comment by jh-bate** [comment]
Good to hear - the switch should be complete in the next week I would guess.
