### ISSUE TITLE
Add more verbose descriptions to repos including key words.

### ISSUE THREAD

**Issue by timberFrame** [tidepool-org/hub#119]
Looking at the list of tidepool inspired names, I think it would be helpful to have more verbose descriptions to the repos.  The tidepool metaphore is meaningful to us, but not the general public.  The descriptions need key words like "diabetes" "BGL" "Cloud" "log" "graph" etc.  That way people doing a google seach will find tidepool.

**Comment by jh-bate** [comment]
good point about having meaningful repo descriptions. We have started updating some of them to provide better links and also some of the keywords that you mention. I will go through the main repos we use and do a sanity check on them and update add were it makes sense to do so.

**Comment by timberFrame** [comment]
Thanks Jamie,

it’s nice to contribute something.

-Matt

**Comment by jh-bate** [comment]
have updated the most relevant repos to include reference to diabetes data and links were applicable
